version: '3.7'

services:
  redis:
    image: redis:7.0
    # command: redis-server --appendonly yes --requirepass botisan
    command: redis-server --appendonly yes
    restart: always
    ports:
      - 6379:6379
    # environment:
    #   - REDIS_PASSWORD=botisan
    volumes:
      - redis:/data
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: botisan
      POSTGRES_PASSWORD: agent
      POSTGRES_DB: botisan-agent
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  postgres:
